version: '3.9'

services:
  chatbot-web:
    build: .
    container_name: chatbot-web-dev
    ports:
      - "8010:8000"
    volumes:
      - .:/app            # MONTA tu c√≥digo local dentro del contenedor
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
